### ISSUE TITLE
kleine Anmerkungen zur Doku und Sensor

### ISSUE THREAD

**Issue by harvey637** [jp112sdl/HB-UNI-Sen-LEV-US#1]
Hi Jerome,,  
Klugscheisseralarm === winzige Anmerkung zur Doku
- ist MaxBotix == MaxSonar? bei den US-Wandlern steht MaxBotix, im unteren Text "Bei Verwendung des MaxSonar ...". Das kann Kleingeister eventuell verwirren.

- In dem Screenshot der Einstellungsseite steht unten "Siehe Datenblatt des Sensor SR04T: mind 20 cm...".
Trotzdem ist im Beispiel "SR04T" ausgewählt und "15 cm" eingetragen. 

Nur so zum "alles richtig verständlich" machen, definitiv vielen Dank und keine Abwertung gemeint!!!
cu
Harvey

PS - ein paar Fragen: 
- spielt die Temperatur keine Rolle? (schon minimal bei der Schallgeschwindigkeit:-)
- Fehlmessung etwa durch Plätschern beim Zulauf z.B. in einen Regenwassertank? 2*messen / Mittelwert?
- Einschränkung des Messwinkels um z.B. Zulauf-Wasserstrahl nicht zu erfassen (10cm Durchmesser Rohr?)

**Comment by jp112sdl** [comment]
- MaxBotix ist der Hersteller, MaxSonar der Produktname (bzw. der Name der Produktfamilie)
- der Screenshot ist halt so... 🤓 der Offset muss individuell eingestellt werden.

- Temperatur ist bei den Distanzen wohl zu vernachlässigen, ich lass mich aber auch gern belehren, falls es Vorschläge zur Einberechnung gibt. Bisher stimmt die Abstandsmessung bei mir auf den Zentimeter genau

Generell sind die Projekte hier nach meinen persönlichen Anforderungen entstanden und "wie sie sind" veröffentlicht (in Bezug auf die letzten beiden Punkte). Sollten Anpassungen wegen eigener Bedürfnisse notwendig werden (denn irgendwie hat jeder andere Umgebungen), ist es dann wohl am besten, mit Forks zu arbeiten.

VG Jérôme

**Comment by harvey637** [comment]
Hi,
mir geht es auch so, für die eigene Anforderung, da hat man ja ein Testumfeld in Praxis.
Bei mir eine Regenwassertonne. Schon der zweite Homematicsensor defekt - Schwitzwasser und 
die Platine sitzt so flach, dass der kleinste Wassertropfen reicht :-(

Als ich damals nach Ideen googlete (vor homematic) fand ich eben auch eine Temperaturkompensation.
Ist ja vielleicht auch in dem Modul selbst eingebaut ... vielleicht. 
Daher auch die Frage nach dem Winkel: bei mir strömt Wasser aus dem Regenfallrohr bei starkem
Regen sehr "intensiv" in die Tonne. Es gibt den Wasser"fall" mitten durch den Raum oberhalb
der Wassers, eventuell durch den Bereich, den der US-Sensor für die Messung braucht. Da war die
damalige Informationslage, dass der Sensor in eiem normalen 10cm Rohr oben drauf ist, das Rohr ein
paar seitliche Löcher hat damit der Wasserspiegel ansteigen kann und nur INNERHALB des Rohres
reflexionsarm die Oberfläche gemessen wird. 
Teile sind in Bestellung :-) Und ich sehe mir das dann gerne "nach persönlichen Anforderungen" an.
Ergibt sich was interessantes melde ich mich hier, sonst ist alles ok!

Wenn ich doch nur mehr von Methoden und Templates verstehen würde, bin halt alter > 64 Jahre
Assemblerprogrammierer. Aber so ein Dutzend HB-Sensoren laufen schon, teils eben mit "persönlichen Anforderungen" modifiziert, die meist uninteressant sind.

Aber das Gesamtthema "Produktsicherheit" (Unterspannung fürhte bei mir zweimal zu Dutycycle mit 
Verlust der Geräteverbindung), eben auch "Messung Wasserspiegel" und nicht "Messung was immer da so rumfliegt". Stetz zu wiederholen, ich achte die freiwillige Arbeit hier sehr und möchte nur - ohne zu stören - auch was zurückliefern.
cu
Haarvey

**Comment by harvey637** [comment]
Ach, auf den Fotos kann ich auch erkennen, das derjenige auch anscheinend ähnlich schlechte 
Erfahrungen mit dem kapazitiven HM-Füllstandssensor hat, die Kabel mit den Abstandhaltern 
ist ja gut zu erkennen.

**Comment by jp112sdl** [comment]
Derjenige bin ich... 😄 
Der kap. Sensor hat mich sehr enttäuscht. Deshalb nun der Versuch mit Ultraschall.
