### ISSUE TITLE
 In function 'void setup()':  HB-UNI-Sen-LEV-US:318:19: error: 'printDeviceInfo' was not declared in this scope

### ISSUE THREAD

**Issue by fastsonic** [jp112sdl/HB-UNI-Sen-LEV-US#2]
Hi,
not sure how to fix:
Version of Arduino 1.8.7
Error:
C:\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\HB-UNI-Sen-LEV-US-4d6f7bfa74beb84f3a6f04ccf81aa3cc47c522d0\HB-UNI-Sen-LEV-US\HB-UNI-Sen-LEV-US.ino: In function 'void setup()':

HB-UNI-Sen-LEV-US:318:19: error: 'printDeviceInfo' was not declared in this scope

**Comment by jp112sdl** [comment]
Hi,

just comment line [#318](https://github.com/jp112sdl/HB-UNI-Sen-LEV-US/blob/4d6f7bfa74beb84f3a6f04ccf81aa3cc47c522d0/HB-UNI-Sen-LEV-US.ino#L318):
`//printDeviceInfo();`
