### ISSUE TITLE
jp112sdl / HB-UNI-Sen-LEV-US

### ISSUE THREAD

**Issue by Passagier** [jp112sdl/HB-UNI-Sen-LEV-US#4]
Hallo Jerome,

ich habe den HB-UNI-Sen-LEV-US nachgebaut wie so einige andere Projekte von Dir auch -  und aktuelle Versionen verwendet, funktioniert alles sehr sehr gut, allerdings habe ich ein kleines Problem nur bei dem HB-UNI-Sen-LEV-US, wenn ich die Werte für Sendeintervall und oder Low-Bat.-Schwelle ändern möchte, werden diese tatsächlich nicht übernommen, es bleibt bei den Defaultwerten Sendeintervall= 180 und Low-Bat.-Schwelle= 2.2
wie kann ich das beheben?

Beste Grüße

**Comment by jp112sdl** [comment]
Nutzt du gerade CCU FW 3.55.5 ?
Da ist ein Bug drin... du kannst bei keinem Gerät irgendwelche Werte mehr ändern

**Comment by Passagier** [comment]
Ja ich habe die CU FW 3.55.5,
stimmt, habe ich gerade beim HB-UNI-Sen-TEMP-DS18B20 probiert gleiches Problem... 
dachte dass er da die Werte übernommen hatte..
Allerdings kann ich die anderen Werte wie Höhe und Breite beim HB-UNI-Sen-LEV-US problemlos ändern
Ist der Bug behebbar oder gibt es ein Workarround?

**Comment by jp112sdl** [comment]
Workaround: webui.js patchen
https://github.com/jens-maus/RaspberryMatic/blob/master/buildroot-external/patches/occu/0098-WebUI-Fix-ProofAndSetValue.patch

Ansonsten auf neue CCU FW warten, oder Downgrade machen

**Comment by Passagier** [comment]
Sehr guter Tipp, danke hat funktioniert. 👍

**Comment by Passagier** [comment]
Hallo Jerome,
ich muss noch einmal nachhacken, 
Nach dem patchen der Webui, kann ich die Konfigurationsdaten eintragen und senden, diese werden aber erst übernommen, wenn ich kurzdarauf den Configbuttion am HB-UNI-Sen-LEV-US betätige oder es kurz vom Strom nehme und dadurch neu gestartet wird, sonst geht die Config nicht durch, woran kann das noch liegen?

**Comment by jp112sdl** [comment]
Hast du keine originalen HM Sensoren?

Das ist übliches Verhalten von batterieversorgten Homematic Sensoren.

**Comment by Passagier** [comment]
Nein, alles auf HMIP, außer den Projekten von Dir,
diese habe ich mit Arduino Nano‘s mit Dauerstrom über USB
im Einsatz, hat bisher sehr gut funktioniert,
Originale HM‘s hab ich keine.

**Comment by Passagier** [comment]
Wünsche Frohe Weihnachten und ein schönes gesundes Fest!

**Comment by jp112sdl** [comment]
Dankeschön, das wünsche ich dir auch

**Comment by Passagier** [comment]
Danke!
