### ISSUE TITLE
Probleme bei der Messung

### ISSUE THREAD

**Issue by ednarb29** [jp112sdl/HB-UNI-Sen-LEV-US#5]
Hallo Jérôme,

Vielen Dank für deine Projekte und deinen Code. Ich bin gerade dabei, diesen Anwendungsfall nachzubauen, da mein Vater ein Wassertank im Keller hat, den er gerne überwachen möchte.

Allerdings stoße ich dabei auf ein Problem bei der Messung. Der Sensor ist oben am Tank angebracht, und der Tank ist auf einem Abstand vom Sensor von etwa 100cm mit einer ersten Verengung versehen, die der Sensor konstant aufgreift. Diese Verengung ist rund und hat einen Durchmesser von etwa 80cm. Eine weitere Verengung ist weiter unten angebracht. Die maximale Distanz, die der Sensor messen muss, beträgt 160cm. Auf dieser Entfernung sollten 15 Grad Messbereich also 42cm ausmachen, was nur die Hälfte der Verengung darstellt.

Hast du eine Idee, warum der Sensor permanent die erste Verengung aufgreift und was das Problem sein könnte? Die 15 Grad auf die Entfernung dürften es eigentlich nicht sein.

Ich habe einen US-100 mit dem Pro Mini verwendet, habe aber auch einen HC-SR04 mit einem Uno und Display Shield testweise in den Tank gehalten - gleiches Problem. Denkst du, ich kann das mit diesem Sensor lösen, oder sollte ich lieber auf den VL53L0X ausweichen (mein Messbereich liegt zwischen 10-160cm etwa).

Danke und Grüße,
Steven

![image](https://user-images.githubusercontent.com/12187445/104852479-8b2dc400-58fb-11eb-8af1-69a3649e06c4.png)

![image](https://user-images.githubusercontent.com/12187445/104852492-98e34980-58fb-11eb-8418-62cae1c580b4.png)

**Comment by jp112sdl** [comment]
Puh, das ist eine schwierige Frage, die ich dir nicht beantworten kann.

Die Tücken der Ultraschallmessungen kenne ich nicht bis ins Detail.
Vielleicht gibt es im Netz irgendwo ein "Ultraschallsensoren-Forum" ? :)

Zum VL53L0X kann ich nur sagen, dass du eine reflektierende Oberfläche benötigst. 
Evtl. ein 100er Rohr reinstellen bis kurz über dem Boden. Dann eine dünne Styroporplatte drinnen auf der Wassersäule schwimmen lassen und den VL53L0X wirklich exakt senkrecht darüber positionieren.

Eine weitere Möglichkeit wäre vielleicht noch den Druck zu messen. 
Der Tank hat einen Anschluss unten rechts auf dem ersten Bild?

**Comment by ednarb29** [comment]
Danke für deine schnelle Antwort. Ja, das ist der Anschluss, wo die Pumpe das Wasser abnimmt.

**Comment by ednarb29** [comment]
@jp112sdl, ich habe nochmal recherchiert zu dem Sensor und [diesen Artikel hier gefunden](https://wolles-elektronikkiste.de/vl53l0x-und-vl53l1x-tof-abstandssensoren). Auch in mehreren Datenblättern habe ich eine maximale (verlässliche) Reichweite von 1m bei dem vl53l0x gefunden. Der vl53l1x scheint aber eine gute Alternative zu sein. Im Keller ist es komplett dunkel, und ich möchte es mit einer schwimmenden Styroporplatte probieren.

[Den Sensor gibt es zum Beispiel hier zu kaufen.](https://eckstein-shop.de/Pololu-VL53L1X-Time-of-Flight-Distance-Sensor-Carrier-with-Voltage-Regulator-400cm-Max)

Ich würde den Sensor gerne ausprobieren, bin aber nicht in der Lage, den [Sensor-Spezifischen Code](https://github.com/jp112sdl/AskSinPP/tree/master/sensors) anzupassen bzw. zu schreiben. Kann ich den Sensor mit deinem Projekt Code [HB-UNI-Sen-LEV-TOF](https://github.com/jp112sdl/HB-UNI-Sen-LEV-TOF) und dem dort verwendeten [Sensor Vl53l0x Code](https://github.com/jp112sdl/AskSinPP/blob/master/sensors/Vl53l0x.h) verwenden, oder muss dazu neuer Code für den Sensor geschrieben werden?

Danke!

**Comment by jp112sdl** [comment]
Der VL53L1X wird mit dem Code nicht funktionieren.
Dazu sind größere Umbauten notwendig.

**Comment by ednarb29** [comment]
Schade... Hättest du Lust / Zeit das umzusetzen?

**Comment by jp112sdl** [comment]
Eher weniger, weil ich die Notwendigkeit gerade nicht sehe.

> Auch in mehreren Datenblättern habe ich eine maximale (verlässliche) Reichweite von 1m bei dem vl53l0x gefunden.

Der Hersteller selbst schreibt nichts davon
https://www.st.com/resource/en/data_brief/vl53l0x.pdf

Der VL53L0X kostet auch keine 2 EUR https://de.aliexpress.com/item/32849648943.html
Daher solltest du es vielleicht erstmal mit dem Sensor probieren

**Comment by ednarb29** [comment]
Alles klar, dann probiere ich das mit dem Sensor und wenn es nicht geht verwerfe ich das Projekt. Danke trotzdem für deine kurze Antwortzeit und Unterstützung! :)

**Comment by ednarb29** [comment]
Habe es jetzt mit dem VL53L0X Sensor probiert und er misst tatsächlich nur bis 120cm, danach zeigt er "out of range" an. Damit kann ich das leider nicht für mein Fass verwenden, da ich etwa 150-160cm benötige, schade.

Bitte lass mich wissen, falls du irgendwann den anderen Sensor unterstützt, dann würde ich es wieder probieren.

Danke und Grüße,
Steven

`#include <LiquidCrystal.h>
LiquidCrystal lcd(8, 9, 4, 5, 6, 7);  // select the pins used on the LCD panel

#include "Adafruit_VL53L0X.h"

Adafruit_VL53L0X lox = Adafruit_VL53L0X();

void setup() {
  Serial.begin(115200);

  lcd.begin(16, 2);

  // wait until serial port opens for native USB devices
  while (! Serial) {
    delay(1);
  }
  
  Serial.println("Adafruit VL53L0X test");
  if (!lox.begin()) {
    Serial.println(F("Failed to boot VL53L0X"));
    while(1);
  }
  // power 
  Serial.println(F("VL53L0X API Simple Ranging example\n\n")); 
}


void loop() {
  VL53L0X_RangingMeasurementData_t measure;
    
  Serial.print("Reading a measurement... ");
  lox.rangingTest(&measure, false); // pass in 'true' to get debug data printout!

  lcd.clear();
  lcd.setCursor(0,0);
  
  if (measure.RangeStatus != 4) {  // phase failures have incorrect data
    Serial.print("Distance (mm): "); Serial.println(measure.RangeMilliMeter);
    lcd.print("D: ");
    lcd.print(measure.RangeMilliMeter,1);
  } else {
    Serial.println(" out of range ");
    lcd.print(" out of range ");
  }

    
  delay(500);
}`

**Comment by ednarb29** [comment]
Hier steht, dass man long range bis 200cm nutzen kann - wie aktiviert man den?

https://www.adafruit.com/product/3317

**Comment by ednarb29** [comment]
Hi, habe es jetzt mit dem VL53L0X probiert. Im einfachen Modus geht er nur bis 120cm, mit diesem Code hier geht er allerdings in den Long Range Modus und bis 200cm. Das ist das, was ich bräuchte. Unterstützt du das in deinem Code auch?

https://github.com/adafruit/Adafruit_VL53L0X/blob/master/examples/vl53l0x_multi_extended/vl53l0x_multi_extended.ino

**Comment by jp112sdl** [comment]
> Unterstützt du das in deinem Code auch?

Ja der LONG_RANGE Modus wird standardmäßig verwendet
https://github.com/jp112sdl/HB-UNI-Sen-LEV-TOF/blob/ae6d07fb8a74e5c2d791c49386c9ada14d37d033/HB-UNI-Sen-LEV-TOF.ino#L137

**Comment by ednarb29** [comment]
Super, danke dir. Dann löte ich das jetzt mal zusammen und probiere es aus. :)

**Comment by ednarb29** [comment]
Ich habe die batterie am RAW und GND pin vom Pro Mini. Schließe ich den Sensor dann an GND, VCC, und A4, A5 an wie hier beschrieben?

https://www.extrafudge.com/site/2019/03/arduino-pro-mini-sda-and-scl-pins/

**Comment by ednarb29** [comment]
Habe es jetzt so angelötet und probiert. Musste eine Library für den VL53L0X von Pololu installiert, sonst hat er sich beschwert, dass die VL53L0X.h fehlt. Ist das die korrekte Lib? Vielleicht in die Readme aufnehmen. Oder ich habs irgendwo überlesen.

Allerdings kommt auf dem Serial Monitor nichts an. Wenn ich den Code für den US aufspiele, läuft er los, mit dem Code für den VL53L0X allerdings nicht. Siehe Screenshots. Ideen?

<img width="541" alt="Screen Shot 2021-01-29 at 21 27 22" src="https://user-images.githubusercontent.com/12187445/106324527-94af1880-6279-11eb-84d5-a19be7ff3338.png">
<img width="896" alt="Screen Shot 2021-01-29 at 21 28 22" src="https://user-images.githubusercontent.com/12187445/106324530-9678dc00-6279-11eb-828f-e05426dda8f7.png">

**Comment by jp112sdl** [comment]
> Vielleicht in die Readme aufnehmen. Oder ich habs irgendwo überlesen.

Ist ein bisschen versteckt
https://github.com/pa-pa/AskSinPP/blob/a836a356103f4a6d1d1ca9517347f145a2b25b26/sensors/Vl53l0x.h#L26

> Allerdings kommt auf dem Serial Monitor nichts an.

https://github.com/jp112sdl/HB-UNI-Sen-LEV-TOF/blob/ae6d07fb8a74e5c2d791c49386c9ada14d37d033/HB-UNI-Sen-LEV-TOF.ino#L137
I2C Adresse 0x29 passt?

**Comment by ednarb29** [comment]
Das weis ich nicht. Wie kann ich das kontrollieren bzw. wie weis ich ob die stimmt? Also habe den Code unverändert aus deinem Repo genommen.

**Comment by jp112sdl** [comment]
I2CScanner probieren.
https://playground.arduino.cc/Main/I2cScanner/

Hab momentan wenig Zeit

**Comment by ednarb29** [comment]
Kein Problem. Ich schaue es mir morgen mal an. Danke vielmals.

Vielleicht hat es auch was mit der Kabellänge zu tun. Habe ein cat7 Ethernet Kabel in den Keller gelegt und den Arduino einen Stock drüber (3m Kabel) wegen dem Funkempfang. Mit dem US ging es problemlos, aber vielleicht macht es das I2C nicht mit...

**Comment by jp112sdl** [comment]
> Habe ein cat7 Ethernet Kabel in den Keller gelegt und den Arduino einen Stock drüber (3m Kabel) wegen dem Funkempfang.

```
 So the maximum bus length of an I2C link is about 1 meter at 100 Kbaud
```
http://www.mosaic-industries.com/embedded-systems/sbc-single-board-computers/freescale-hcs12-9s12-c-language/instrument-control/i2c-bus-specifications

100k ist die Standardübertragungsrate (beim Arduino)

**Comment by ednarb29** [comment]
Danke dir. Habe das Kabel abgeschnitten und so kurz wie möglich gemacht. Mit knapp 1,5m geht es. Auch der Sensor scheint zu funktionieren und korrekt zu messen. Habe eine Styroporplatte an einer Angelschnur und einem Gewicht am Boden des Fasses befestigt, um eine beweglicht Fläche zu haben.

Alles in allem funktioniert es jetzt jedenfalls. Nochmals vielen Dank für deine Unterstützung!
